model:
  model_class: litellm_response
  cost_tracking: ignore_errors
  model_kwargs:
    api_base: https://api.openlux.ai/v1
    timeout: 120
    extra_headers:
      User-Agent: Mozilla/5.0
    reasoning:
      effort: xhigh
    drop_params: false
agent:
  step_limit: 150
